import Layout from "@/components/Layout";
import Head from "next/head";
import Image from "next/image";
import ProfilePic from "../../public/images/profile/developer-pic-1.png";
import Pic from "../../public/images/profile/reactjsnextjs.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";

export default function Home() {
  return (
    <>
      <Head>
        <title>Abdul Hannan Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex items-center text-dark w-full min-h-screen ">
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image src={ProfilePic} alt="Abdul Hannan" />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text={"Fiverr Level-1 Freelancer."}
                className="!text-6xl !text-left"
              />
              <p className="my-4 text-base font-medium">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js and
                web development.
              </p>
              <div className="flex self-start items-center mt-2">
                <Link
                  href={"/dummy.pdf"}
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 text-lg font-semibold rounded-lg border-2 border-solid border-transparent hover:border-dark hover:bg-light hover:text-dark"
                  download={true}
                >
                  Resume <LinkArrow className={"w-5 ml-2"} />
                </Link>
                <Link
                  href={"mailto:abdulhani232@gmail.com"}
                  target="_blank"
                  className="ml-4 text-lg text-gray-600 font-medium capitalize underline
                "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
// Fiverr Level-1 Freelancer.
// "Turning Vision Into Reality With Code And Design."
